services:
  derper:
    build: .
    container_name: derper
    restart: ${DERP_RESTART_POLICY:-unless-stopped}
    ports:
      - "${DERP_MAP_HTTPS_PORT}:${DERP_HTTPS_PORT}"
      - "${DERP_MAP_STUN_PORT}:${DERP_STUN_PORT}/udp"
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ./certs:/app/certs
      - ./data:/var/lib/derper
      - ./logs:/var/log/derper
    environment:
      - TZ=${TZ}
    networks:
      - traefik_net
    command:
      - "/app/derper"
      - "--hostname=${DERP_HOSTNAME}"
      - "-a=:${DERP_HTTPS_PORT}"
      - "--stun"
      - "--stun-port=${DERP_STUN_PORT}"
      - "--verify-clients=${DERP_VERIFY_CLIENTS}"
      - "--certmode=${DERP_CERT_MODE}"
      - "--certdir=/app/certs"

networks:
  traefik_net:
    external: true
